version: '3'
services:
  backend:
    build:
      context: ./App
      dockerfile: ./Dockerfile
    restart: always
    ports:
     - "5000:5000"
    
  frontend:
    build:
      context: ./frontApp
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
      
